package javathreads.recipe06;

import static java.lang.String.format;

import java.util.Date;
import java.util.Deque;
import java.util.concurrent.TimeUnit;

/**
 * @author mropotica
 */
public class WriterTask implements Runnable {

	private Deque<Event> deque;

	public WriterTask(Deque<Event> deque) {
		this.deque = deque;
	}

	@Override
	public void run() {

		for (int i = 0; i < 60; i++) {

			Date date = new Date();
			String eventName = format("Event generated by %s at %d", Thread.currentThread().getName(), date.getTime());
			Event event = new Event(eventName, new Date());
			deque.addFirst(event);

			try {
				TimeUnit.SECONDS.sleep(1);
			} catch (InterruptedException e) {
				e.printStackTrace();
			}
		}
	}
}
